### ISSUE TITLE
TI Sensing Patch usable?

### ISSUE THREAD

**Issue by manuelknott** [KoopCoop/Cyclino#1]
Hi,

I am wondering if it is possible to use this purchasable TI Sensing Patch:

http://www.ti.com/lit/an/sloa212a/sloa212a.pdf

For my understanding it is possible to attach a battery and using a RF430FRL152H instead of a RF430FRL153H should make no difference, am I right?

Thank you very much in advance!
Cheers,
Manuel

**Comment by KoopCoop** [comment]
Yes, you are right, of course. But for the project I have in mind, the smaller antenna size of the freestyle libre is of convenience. And with the integrated battery holder, the PCB is less fragile. Also, neither soldering iron nor soldering paste is needed for the freestyle libre PCB: a frying pan on a stove can be used to solder the rf430frl152h/153h on (and Abbott's chip off) the board. This way, I already produced about 8 of them without failure. This is great for desperate housewives ;-)
I just use the rf430frl153h because it is cheaper.

**Comment by KoopCoop** [comment]
Also, Mouser is the only supplier, with shipping costs of 20€ to Europe. And it is (officially) forbidden to even give away extra sensing patches for free to someone else (in Europe) after having them bought from Mouser. With Abbott's sensors or the bare chips, one does not need to worry.

**Comment by manuelknott** [comment]
Thanks for your quick answer. Now I clearly see the advantages of using the FreestyleLibre Board. 

In the readme you write:

> The pin configuration of Abbott's ASIC varies from the Rf430frl153h. Therefore, two traces on the PCB need to be cut, a resistor has to be taken off and only the ICs internal temperature sensor of the IC is used.

I assume this is necessary when using the FreestyleLibre Board, right? Where do I get information about the specific traces and resistor from?

Is it possible to purchase a modified sensor board from you, although I am not a desperate housewife? ;)
If so, please let me know how to contact you.

Best Greetings

**Comment by KoopCoop** [comment]
There are disadvantages of the Freestyle Libre board as well: only the internal temperature sensor can be used (without more difficult modifications or reprogramming the original Freestyle Libre chip). This sensor has to be calibrated with (at least) a 1-Point calibration, which is already supported by the App.

The batteryless sensing Patch from Ti works out of the box, yes. 
I am not 100 percent sure if cutting the traces/solderling off the resistor is absolutely necessary (EDIT: it is not!), replacing or reprogramming the chip is definitively. It was a measure of precaution,  is easy to do and works. Never change a running system...
I am preparing instructions, I just need more time.

It would be legal for me to give away PCBs where everything I believe to be necessary is taken away. I could also give you a spare chip. But if I would attach the new chip, this would be a new product which would need to be FCC (+WEEE+CE...) certified first. I will contact you.

**Comment by KoopCoop** [comment]
Okay, I am New to github. You may contact me via xxengineering@outlook.de

**Comment by KoopCoop** [comment]
I strongly recomment contacting me. I may know someone who has fully prepared sensors for you.
